name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Black Code Formatter
        uses: psf/black@stable
