name: Upload

on:
  push:
    tags:
      - v*.*.*

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stuff
        run: |
          sudo apt-get update
          sudo apt-get install poppler-utils -y
          sudo apt-get install python3-pip -y
          pip install -r requirements-ci.txt
      - name: Upload portraits
        working-directory: judge_pics/
        run: |
          python3 upload.py \
          -a ${{ secrets.AWS_ACCESS_KEY }} \
          -s ${{ secrets.AWS_SECRET_KEY }}
      - name: Install packaging
        run: python -m pip install -U packaging
      - name: Publish package
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.pypi_token }}
          build: true
